export type GlossaryCategory =
  | "drilling"
  | "logging"
  | "reservoir"
  | "production"
  | "geology"
  | "fluids"
  | "completion"
  | "hse";

export interface GlossaryTerm {
  abbr: string;
  full: string;
  def: string;
  cat: GlossaryCategory;
  lesson?: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { abbr: "ROP", full: "Rate of Penetration", def: "Matkabın suxura nüfuzetmə sürəti. ft/saat və ya m/saat ilə ölçülür.", cat: "drilling", lesson: "drilling" },
  { abbr: "WOB", full: "Weight on Bit", def: "Qazıma zamanı matkaba tətbiq edilən şaquli yük. klb ilə ölçülür.", cat: "drilling", lesson: "drilling" },
  { abbr: "RPM", full: "Rotations Per Minute", def: "Qazıma sütununun dövr sayı. Qazıma sürəti və süxur növü ilə tənzimlənir.", cat: "drilling", lesson: "drilling" },
  { abbr: "ECD", full: "Equivalent Circulating Density", def: "Dövriyyə zamanı qazıma fluidinin effektiv sıxlığı — statik sıxlıq + sürtünmə təzyiqi.", cat: "drilling", lesson: "drilling" },
  { abbr: "BHA", full: "Bottom Hole Assembly", def: "Quyu dibindəki matbaq, stabilizatorlar, əyrilik alətlərinin yığımı.", cat: "drilling", lesson: "drilling" },
  { abbr: "MW", full: "Mud Weight", def: "Qazıma məhlulunun sıxlığı. ppg ilə ifadə edilir.", cat: "drilling", lesson: "drilling" },
  { abbr: "BOP", full: "Blowout Preventer", def: "Quyudan nəzarətsiz axını dayandıran təhlükəsizlik klapanı sistemi.", cat: "drilling" },
  { abbr: "POOH", full: "Pull Out of Hole", def: "Qazıma sütununun quyudan çıxarılması əməliyyatı.", cat: "drilling" },
  { abbr: "RIH", full: "Run In Hole", def: "Qazıma sütununun quyuya salınması əməliyyatı.", cat: "drilling" },
  { abbr: "TD", full: "Total Depth", def: "Quyunun qazındığı maksimum dərinlik.", cat: "drilling" },
  { abbr: "TVD", full: "True Vertical Depth", def: "Quyunun şaquli dərinliyi. Əyri quyularda MD-dən fərqlənir.", cat: "drilling" },
  { abbr: "MD", full: "Measured Depth", def: "Quyunun ağzından ölçülən faktiki boyu.", cat: "drilling" },
  { abbr: "KOP", full: "Kickoff Point", def: "Əyri qazımaya başlanılan dərinlik nöqtəsi.", cat: "drilling" },
  { abbr: "DLS", full: "Dog Leg Severity", def: "Quyunun istiqamət dəyişmə sürəti. °/100ft ilə ölçülür.", cat: "drilling" },
  { abbr: "MWD", full: "Measurement While Drilling", def: "Qazıma əməliyyatı zamanı real vaxtda quyu parametrlərinin ölçülməsi.", cat: "drilling" },
  { abbr: "LWD", full: "Logging While Drilling", def: "Qazıma zamanı karotaj məlumatlarının toplanması texnologiyası.", cat: "drilling" },
  { abbr: "PDC", full: "Polycrystalline Diamond Compact", def: "Yüksək ROP üçün istifadə edilən müasir qazıma matkabı növü.", cat: "drilling" },
  { abbr: "SIDPP", full: "Shut-In Drill Pipe Pressure", def: "Quyu bağlı olduqda qazıma borusundakı təzyiq. Kick intensivliyini müəyyən edir.", cat: "drilling" },
  { abbr: "SICP", full: "Shut-In Casing Pressure", def: "Quyu bağlı olduqda qazıma ilə korpus arasındakı annular təzyiq.", cat: "drilling" },
  { abbr: "FIT", full: "Formation Integrity Test", def: "Formasiyanın möhkəmliyini yoxlamaq üçün aparılan test.", cat: "drilling" },
  { abbr: "LOT", full: "Leak Off Test", def: "Formasiyanın sızma təzyiqini müəyyən etmək üçün aparılan test.", cat: "drilling" },
  { abbr: "WHP", full: "Wellhead Pressure", def: "Quyu başlığındakı təzyiq.", cat: "drilling" },
  { abbr: "HWDP", full: "Heavy Weight Drill Pipe", def: "Ağır çəkili qazıma borusu. BHA ilə adi boru arasında keçid elementi.", cat: "drilling" },
  { abbr: "DC", full: "Drill Collar", def: "WOB yaratmaq üçün istifadə edilən ağır, qalın divarlı qazıma borusu.", cat: "drilling" },
  { abbr: "HSI", full: "Hydraulic Horsepower per Square Inch", def: "Matkab üzərindəki hidravlik güc sıxlığı.", cat: "drilling" },
  { abbr: "SPM", full: "Strokes Per Minute", def: "Qazıma nasosunun tezliyi. Axın sürətini tənzimləmək üçün istifadə edilir.", cat: "drilling" },
  { abbr: "COP", full: "Cost Per Foot", def: "Hər fut qazımanın dəyəri. Qazıma optimizasiyasında əsas KPI.", cat: "drilling" },
  { abbr: "TFA", full: "Total Flow Area", def: "Matkab məmələrinin ümumi axış sahəsi.", cat: "drilling" },
  { abbr: "NDS", full: "Non-Drilling Surprises", def: "Qazıma zamanı planlaşdırılmamış hadisələr.", cat: "drilling" },
  { abbr: "DDI", full: "Drilling Difficulty Index", def: "Quyu qazımasının çətinlik dərəcəsini qiymətləndirən göstərici.", cat: "drilling" },

  { abbr: "GR", full: "Gamma Ray", def: "Təbii radioaktivliyi ölçən karotaj. Gilli süxurlar yüksək, qumtaşlar aşağı GR göstərir.", cat: "logging", lesson: "well-log" },
  { abbr: "SP", full: "Spontaneous Potential", def: "Qazıma məhlulu ilə formasiya suyu arasındakı elektrokimyəvi potensial fərqi.", cat: "logging", lesson: "well-log" },
  { abbr: "RT", full: "True Resistivity", def: "Formasiyanın həqiqi müqaviməti. Yüksək RT neft/qaz işarəsi ola bilər.", cat: "logging", lesson: "well-log" },
  { abbr: "NPHI", full: "Neutron Porosity Index", def: "Neytron karotajından hesablanan məsaməlilik. Qaz zonalarında RHOB ilə ayrılır.", cat: "logging", lesson: "well-log" },
  { abbr: "RHOB", full: "Bulk Density", def: "Həcmi sıxlıq karotajı. g/cc ilə ölçülür.", cat: "logging", lesson: "well-log" },
  { abbr: "DT", full: "Delta-T Sonic", def: "Ses dalğasının sürəti. Məsaməlilik və litologiya təyinində istifadə edilir. μs/ft.", cat: "logging", lesson: "well-log" },
  { abbr: "LLD", full: "Laterolog Deep", def: "Dərin müqavimət ölçən karotaj.", cat: "logging", lesson: "well-log" },
  { abbr: "LLS", full: "Laterolog Shallow", def: "Dayaz müqavimət ölçən karotaj. İşğal zonasını göstərir.", cat: "logging" },
  { abbr: "MSFL", full: "Micro-Spherically Focused Log", def: "Çox dayaz müqavimət ölçən karotaj. Rxo dəyərini verir.", cat: "logging" },
  { abbr: "PE", full: "Photoelectric Factor", def: "Litologiya müəyyən etmək üçün karotaj. Karbonatlarda PE≈5, qumtaşda≈1.8.", cat: "logging" },
  { abbr: "CAL", full: "Caliper Log", def: "Quyu diametrini ölçən karotaj. Kavernaları aşkar edir.", cat: "logging" },
  { abbr: "FMI", full: "Formation Micro Imager", def: "Quyu divarının yüksək çözünürlüklü görüntüsü. Çatları aşkar edir.", cat: "logging" },
  { abbr: "NMR", full: "Nuclear Magnetic Resonance", def: "Maye doyumluluğunu və məsamə ölçüsünü müəyyən edən karotaj.", cat: "logging" },
  { abbr: "MDT", full: "Modular Dynamic Tester", def: "Quyuda təzyiq ölçmə və nümunə götürmə aləti.", cat: "logging" },
  { abbr: "VSP", full: "Vertical Seismic Profile", def: "Quyuda seysmik dalğaların qeydə alınması.", cat: "logging" },
  { abbr: "LAS", full: "Log ASCII Standard", def: "Quyu karotaj məlumatlarının saxlandığı standart fayl formatı.", cat: "logging", lesson: "well-log" },
  { abbr: "Rw", full: "Formation Water Resistivity", def: "Formasiya suyunun müqaviməti. Sw hesablamasında istifadə olunur.", cat: "logging" },
  { abbr: "Rxo", full: "Flushed Zone Resistivity", def: "Qazıma məhlulunun süxura hopduğu zonanın müqaviməti.", cat: "logging" },
  { abbr: "VSH", full: "Volume of Shale", def: "Süxurun içindəki gil həcm fraksiyası. GR karotajından hesablanır.", cat: "logging", lesson: "well-log" },
  { abbr: "IGR", full: "Gamma Ray Index", def: "Normallaşdırılmış GR dəyəri. IGR=(GR−GRmin)/(GRmax−GRmin).", cat: "logging", lesson: "well-log" },

  { abbr: "OOIP", full: "Original Oil in Place", def: "Rezervuardakı ilkin neft həcmi. V×φ×(1−Sw)/Bo düsturu ilə hesablanır.", cat: "reservoir", lesson: "reservoir" },
  { abbr: "OGIP", full: "Original Gas in Place", def: "Rezervuardakı ilkin qaz həcmi. Volumetrik üsulla hesablanır.", cat: "reservoir" },
  { abbr: "φ", full: "Porosity", def: "Süxurun məsamə həcminin ümumi həcmə nisbəti. % ilə ifadə edilir.", cat: "reservoir", lesson: "reservoir" },
  { abbr: "k", full: "Permeability", def: "Süxurun fluidin axışına mane olmaması qabiliyyəti. mD ilə ölçülür.", cat: "reservoir", lesson: "reservoir" },
  { abbr: "Sw", full: "Water Saturation", def: "Məsamə həcminin su ilə doldurulma nisbəti. Archie tənliyi ilə hesablanır.", cat: "reservoir", lesson: "reservoir" },
  { abbr: "So", full: "Oil Saturation", def: "Məsamə həcminin neftlə doldurulma nisbəti. So=1−Sw−Sg.", cat: "reservoir" },
  { abbr: "Sg", full: "Gas Saturation", def: "Məsamə həcminin qazla doldurulma nisbəti.", cat: "reservoir" },
  { abbr: "Swirr", full: "Irreducible Water Saturation", def: "Rezervuardan çıxarıla bilməyən minimum su miqdarı.", cat: "reservoir", lesson: "reservoir" },
  { abbr: "Sor", full: "Residual Oil Saturation", def: "Süzülmədən sonra saxlanan qalıq neft. EOR-un hədəfidir.", cat: "reservoir" },
  { abbr: "GOR", full: "Gas-Oil Ratio", def: "Neftə görə çıxan qazın həcm nisbəti. scf/STB.", cat: "reservoir", lesson: "reservoir" },
  { abbr: "WOR", full: "Water-Oil Ratio", def: "Neftə görə çıxan suyun nisbəti.", cat: "reservoir" },
  { abbr: "WC", full: "Water Cut", def: "Ümumi mayenin içindəki suyun faizi.", cat: "reservoir" },
  { abbr: "Bo", full: "Oil Formation Volume Factor", def: "Rezervuar şəraitindəki neftin yer səthi həcminə nisbəti. rb/STB.", cat: "reservoir" },
  { abbr: "Bg", full: "Gas Formation Volume Factor", def: "Rezervuar şəraitindəki qazın yer səthi həcminə nisbəti.", cat: "reservoir" },
  { abbr: "Rs", full: "Solution Gas-Oil Ratio", def: "Neftdə həll olmuş qazın miqdarı. scf/STB.", cat: "reservoir" },
  { abbr: "Pb", full: "Bubble Point Pressure", def: "Neftdən ilk qaz qabarcığının ayrıldığı təzyiq.", cat: "reservoir" },
  { abbr: "Pi", full: "Initial Reservoir Pressure", def: "Rezervuarın ilkin kəşf edildiyi zamankı təzyiq.", cat: "reservoir" },
  { abbr: "Pr", full: "Reservoir Pressure", def: "Hazırkı rezervuar təzyiqi.", cat: "reservoir" },
  { abbr: "RF", full: "Recovery Factor", def: "Hasilata verilə bilən neftin OOIP-ə nisbəti. Ortalama 20–40%.", cat: "reservoir" },
  { abbr: "EUR", full: "Estimated Ultimate Recovery", def: "Quyunun bütün ömrü boyunca hasilat edəcəyi ümumi həcm.", cat: "reservoir" },
  { abbr: "OWC", full: "Oil-Water Contact", def: "Rezervuarda neft ilə suyun kontakt səthi.", cat: "reservoir" },
  { abbr: "GOC", full: "Gas-Oil Contact", def: "Qaz qapağı ilə neft zonasının kontakt səthi.", cat: "reservoir" },
  { abbr: "GWC", full: "Gas-Water Contact", def: "Qaz ilə su zonasının kontakt səthi.", cat: "reservoir" },
  { abbr: "Kro", full: "Relative Permeability to Oil", def: "Neftin effektiv keçiriciliyinin mütləq keçiriciliyə nisbəti.", cat: "reservoir" },
  { abbr: "Krw", full: "Relative Permeability to Water", def: "Suyun effektiv keçiriciliyinin mütləq keçiriciliyə nisbəti.", cat: "reservoir" },
  { abbr: "Pc", full: "Capillary Pressure", def: "Məsamədəki iki faza arasındakı təzyiq fərqi.", cat: "reservoir" },
  { abbr: "MBE", full: "Material Balance Equation", def: "Rezervuardakı maddə balansını ifadə edən əsas tənlik.", cat: "reservoir" },
  { abbr: "EOR", full: "Enhanced Oil Recovery", def: "Birincil və ikincil üsullardan sonra tətbiq edilən hasilat artırma texnologiyaları.", cat: "reservoir" },
  { abbr: "WAG", full: "Water Alternating Gas", def: "Su və qazın növbələşərək yeridilib çıxarışın artırıldığı EOR üsulu.", cat: "reservoir" },
  { abbr: "SCAL", full: "Special Core Analysis", def: "Nisbi keçiricilik, kapilyar təzyiq kimi parametrləri müəyyən edən nüvə analizləri.", cat: "reservoir" },

  { abbr: "IPR", full: "Inflow Performance Relationship", def: "Quyu dibi axış təzyiqi ilə hasilat debiti arasındakı əlaqəni göstərən əyri.", cat: "production", lesson: "production" },
  { abbr: "VLP", full: "Vertical Lift Performance", def: "Quyunun şaquli hissəsindəki axış xarakteristikası. IPR ilə kəsişməsi işçi nöqtəni verir.", cat: "production", lesson: "production" },
  { abbr: "ESP", full: "Electric Submersible Pump", def: "Dərin quyularda neft qaldırmaq üçün elektrik sualtı nasosu.", cat: "production", lesson: "production" },
  { abbr: "DCA", full: "Decline Curve Analysis", def: "Hasilatın zamanla azalmasını modelləşdirərək gələcəyi proqnozlaşdırır.", cat: "production", lesson: "production" },
  { abbr: "PI", full: "Productivity Index", def: "Hasilat debiti ilə drawdown nisbəti. STB/day/psi.", cat: "production", lesson: "production" },
  { abbr: "AOF", full: "Absolute Open Flow", def: "Quyunun maksimum nəzəri hasilat potensialı.", cat: "production" },
  { abbr: "FBHP", full: "Flowing Bottomhole Pressure", def: "Quyu istehsal edərkən quyu dibindəki təzyiq.", cat: "production" },
  { abbr: "SBHP", full: "Static Bottomhole Pressure", def: "Quyu bağlı olduqda tarazlaşmış quyu dibi təzyiqi.", cat: "production" },
  { abbr: "Pwf", full: "Flowing Wellbore Pressure", def: "İstehsal zamanı quyu dibindəki təzyiq.", cat: "production" },
  { abbr: "GLR", full: "Gas-Liquid Ratio", def: "Ümumi mayeyə görə qaz nisbəti. Gas lift optimizasiyasında istifadə olunur.", cat: "production" },
  { abbr: "WI", full: "Water Injection", def: "Rezervuar təzyiqini saxlamaq üçün suyu yeritmə üsulu.", cat: "production" },
  { abbr: "SRP", full: "Sucker Rod Pump", def: "Dayaz quyularda mexaniki nasos sistemi.", cat: "production" },
  { abbr: "PCP", full: "Progressive Cavity Pump", def: "Yüksək özlülüklü neftlər üçün vintli nasos.", cat: "production" },
  { abbr: "THP", full: "Tubing Head Pressure", def: "Tüp başlığındakı təzyiq.", cat: "production" },
  { abbr: "CHP", full: "Casing Head Pressure", def: "Korpus başlığındakı annular təzyiq.", cat: "production" },
  { abbr: "Nodal", full: "Nodal Analysis", def: "Quyu sistemini komponentlərə ayıraraq optimal iş nöqtəsini tapmaq üsulu.", cat: "production", lesson: "production" },
  { abbr: "Di", full: "Initial Decline Rate", def: "DCA-da ilkin hasilat azalma sürəti.", cat: "production" },
  { abbr: "b", full: "Hyperbolic Decline Exponent", def: "Arps tənliyindəki b faktoru. 0=eksponensial, 1=harmonik.", cat: "production" },
  { abbr: "OPEX", full: "Operating Expenditure", def: "Quyunun gündəlik işletmə xərci.", cat: "production" },
  { abbr: "CAPEX", full: "Capital Expenditure", def: "Quyu qazıması və infrastruktur üçün kapital xərcləri.", cat: "production" },
  { abbr: "NPV", full: "Net Present Value", def: "Layihənin cari dəyərə çevrilmiş xalis gəliri.", cat: "production" },
  { abbr: "IRR", full: "Internal Rate of Return", def: "NPV-ni sıfıra bərabər edən diskont dərəcəsi.", cat: "production" },

  { abbr: "TOC", full: "Total Organic Content", def: "Ana süxurun üzvi maddə miqdarı. Karbohidrogen generasiya potensialını göstərir.", cat: "geology", lesson: "geology" },
  { abbr: "Ro", full: "Vitrinite Reflectance", def: "Üzvi maddənin yetkinlik göstəricisi. 0.6–1.3% neft pəncərəsidir.", cat: "geology", lesson: "geology" },
  { abbr: "API", full: "API Gravity", def: "Neftin sıxlığını göstərən ölçü vahidi. >40 yüngül, <20 ağır neftdir.", cat: "geology", lesson: "geology" },
  { abbr: "AVO", full: "Amplitude Variation with Offset", def: "Seysmik işarənin amplitudasının ofset ilə dəyişməsi. Fluid işarəsidir.", cat: "geology" },
  { abbr: "DHI", full: "Direct Hydrocarbon Indicator", def: "Karbohidrogen mövcudluğunu birbaşa göstərən seysmik əlamət.", cat: "geology" },
  { abbr: "TWT", full: "Two-Way Time", def: "Seysmik dalğanın gedib-qayıtma vaxtı. ms ilə ölçülür.", cat: "geology" },
  { abbr: "DIP", full: "Formation Dip", def: "Süxur laylının üfüqdən bucaq meyli.", cat: "geology" },
  { abbr: "NET", full: "Net Pay", def: "Hasilat edə biləcək effektiv lay qalınlığı.", cat: "geology" },
  { abbr: "Tmax", full: "Temperature of Maximum Pyrolysis", def: "Rock-Eval pirolizindəki maksimum temperatur. Ana süxur yetkinliyini göstərir.", cat: "geology" },
  { abbr: "HI", full: "Hydrogen Index", def: "Piroliz testindən alınan karbohidrogen generasiya potensialı. mg HC/g TOC.", cat: "geology" },
  { abbr: "GIP", full: "Gas in Place", def: "Rezervuardakı qazın ümumi həcmi.", cat: "geology" },

  { abbr: "PVT", full: "Pressure-Volume-Temperature", def: "Rezervuar fluidinin faza davranışını xarakterizə edən xassələr kompleksi.", cat: "fluids" },
  { abbr: "EOS", full: "Equation of State", def: "Fluidin P-V-T davranışını modelləşdirən tənlik.", cat: "fluids" },
  { abbr: "CGR", full: "Condensate-Gas Ratio", def: "Qaza görə kondensatın nisbəti. STB/MMscf.", cat: "fluids" },
  { abbr: "µo", full: "Oil Viscosity", def: "Neftin axış müqaviməti. cp ilə ölçülür.", cat: "fluids" },
  { abbr: "IFT", full: "Interfacial Tension", def: "İki faza arasındakı səthi gərginlik. mN/m. EOR üçün kritikdir.", cat: "fluids" },
  { abbr: "SG", full: "Specific Gravity", def: "Fluidin suyun və ya havanın sıxlığına nisbəti.", cat: "fluids" },
  { abbr: "z", full: "Gas Compressibility Factor", def: "Real qazın ideal qazdan sapmasını göstərən faktor.", cat: "fluids" },
  { abbr: "Bw", full: "Water Formation Volume Factor", def: "Rezervuardakı suyun yer səthi şəraitindəki həcmə nisbəti.", cat: "fluids" },
  { abbr: "Co", full: "Oil Compressibility", def: "Neftin sıxıla bilmə qabiliyyəti. psi⁻¹.", cat: "fluids" },
  { abbr: "PR-EOS", full: "Peng-Robinson Equation of State", def: "Karbohidrogen sistemlərini modelləşdirmək üçün ən çox istifadə edilən hal tənliyi.", cat: "fluids" },

  { abbr: "PERF", full: "Perforations", def: "Korpus borusunda formasiyaya keçid üçün açılan deşiklər.", cat: "completion" },
  { abbr: "FRAC", full: "Hydraulic Fracturing", def: "Formasiyaya yüksək təzyiqli maye yeridərək keçiriciliyi artırma.", cat: "completion" },
  { abbr: "SRV", full: "Stimulated Reservoir Volume", def: "Hidravlik parçalanma ilə stimulyasiya edilən rezervuar həcmi.", cat: "completion" },
  { abbr: "ISIP", full: "Instantaneous Shut-In Pressure", def: "Hidravlik parçalanma dayandırıldıqdan dərhal sonra ölçülən təzyiq.", cat: "completion" },
  { abbr: "FCP", full: "Fracture Closure Pressure", def: "Hidravlik çatın bağlandığı təzyiq.", cat: "completion" },
  { abbr: "PKR", full: "Packer", def: "Quyu içərisini izolyasiya etmək üçün möhürləyici avadanlıq.", cat: "completion" },
  { abbr: "ICD", full: "Inflow Control Device", def: "Bərabər axını təmin edən tamamlama aləti.", cat: "completion" },
  { abbr: "CT", full: "Coiled Tubing", def: "Sarılmış borular vasitəsilə aparılan quyu daxili müdaxilə əməliyyatları.", cat: "completion" },
  { abbr: "DHSV", full: "Downhole Safety Valve", def: "Quyu daxilindəki avtomatik bağlanan təhlükəsizlik klapanı.", cat: "completion" },
  { abbr: "SPF", full: "Shots Per Foot", def: "Perforasiya zolağında hər fut üçün atış sayı.", cat: "completion" },
  { abbr: "WL", full: "Wireline", def: "Kabel vasitəsilə aparılan quyu içi əməliyyatlar.", cat: "completion" },

  { abbr: "HSE", full: "Health, Safety and Environment", def: "Sağlamlıq, Təhlükəsizlik və Ətraf Mühit idarəetmə sistemi.", cat: "hse" },
  { abbr: "HAZOP", full: "Hazard and Operability Study", def: "Proses təhlükəliliyini müəyyən etmək üçün sistematik analiz üsulu.", cat: "hse" },
  { abbr: "PTW", full: "Permit to Work", def: "Təhlükəli əməliyyatlar üçün verilən rəsmi icazə sənədi.", cat: "hse" },
  { abbr: "LOTO", full: "Lock-Out Tag-Out", def: "Enerjini izolyasiya etmək üçün kilidlə nişanlamaq proseduru.", cat: "hse" },
  { abbr: "H2S", full: "Hydrogen Sulfide", def: "Çox zəhərli qaz. 10 ppm həyəcan, 100 ppm həyat üçün təhlükəlidir.", cat: "hse" },
  { abbr: "PPE", full: "Personal Protective Equipment", def: "Fərdi mühafizə vasitələri — kask, eynək, əlcək.", cat: "hse" },
  { abbr: "LEL", full: "Lower Explosive Limit", def: "Yanıcı qazın partlama üçün minimum konsentrasiyası.", cat: "hse" },
  { abbr: "SIL", full: "Safety Integrity Level", def: "Təhlükəsizlik funksiyasının etibarlılıq dərəcəsi. SIL 1–4.", cat: "hse" },
  { abbr: "ERP", full: "Emergency Response Plan", def: "Fövqəladə hallarda hərəkət qaydaları planı.", cat: "hse" },
  { abbr: "SIMOPS", full: "Simultaneous Operations", def: "Eyni ərazidə eyni vaxtda aparılan bir neçə əməliyyat.", cat: "hse" },
  { abbr: "MSDS", full: "Material Safety Data Sheet", def: "Kimyəvi maddənin təhlükəlilik xüsusiyyətlərini əks etdirən məlumat vərəqəsi.", cat: "hse" },
  { abbr: "HSSE", full: "Health, Safety, Security and Environment", def: "HSE-yə Təhlükəsizlik əlavə edilmiş genişləndirilmiş sistem.", cat: "hse" },
];

export const CATEGORY_LABELS: Record<GlossaryCategory, string> = {
  drilling: "Drilling",
  logging: "Well Logging",
  reservoir: "Reservoir",
  production: "Production",
  geology: "Geology",
  fluids: "Fluids & PVT",
  completion: "Completion",
  hse: "HSE",
};

export const LESSON_LABELS: Record<string, string> = {
  drilling: "Drilling",
  "well-log": "Quyu Loqları",
  reservoir: "Rezervuar",
  production: "Hasilat",
  geology: "Geologiya",
};